name: Create GitHub Repo

on:
  workflow_dispatch:
    inputs:
      repoName:
        description: 'Repository Name'
        required: true

jobs:
  create-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Repository
      id: create_repo
      run: |
        REPO_NAME="${{ github.event.inputs.repoName }}"
        GH_PAT="${{ secrets.GH_PAT }}"
        
        # Create the repository using the GitHub API
        curl -X POST -H "Authorization: token $GH_PAT" \
          https://api.github.com/user/repos -d "{\"name\":\"$REPO_NAME\"}"
        
        echo "::set-output name=repository_name::${REPO_NAME}"
      shell: bash

    - name: Get Repository Name
      run: echo "Repository Name: ${{steps.create_repo.outputs.repository_name}}"
