name: assist-accelerator-infrastructure
on:
  workflow_dispatch:
    inputs:
     name:
       description: 'Select Deployment Environment'
       type: choice
       options:
       - demo_openai
       - dev_openai
       - sbx_jd
       - sbx_trp
concurrency:
  group: assist-accelerator-infrastructure
  cancel-in-progress: false  # TODO - This may not be a good idea on an infra deploy - TRP (06/22/2023)

jobs:
  deploy:
    environment:
      name: test-infra
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: |
          ./deploy1.ps1 ${{ github.event.inputs.name }}

    
